#!/usr/bin/env python3
"""Generate auto-sync Markdown snippets for MASTER document metrics tables."""

from __future__ import annotations

import csv
import json
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

PROJECT_ROOT = Path(__file__).resolve().parent.parent
LOG_DIR = PROJECT_ROOT / "logs_sdavt_v3_r4"
QUEUE_FILE = PROJECT_ROOT / "outputs_sdavt_v3_r4" / "experiment_queue.json"
AUDIT_FILE = PROJECT_ROOT / "outputs_sdavt_v3_r4" / "tables" / "r4_training_audit.json"
OUT_DIR = PROJECT_ROOT / "outputs_sdavt_v3_r4" / "status"
SNIPPET = OUT_DIR / "master_doc_metrics_snippet.md"
CHAMPION_SNIPPET = OUT_DIR / "master_doc_champions_snippet.md"


def _f(v: Any) -> Optional[float]:
    if v is None or str(v).strip() == "":
        return None
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def read_best(metrics_csv: Path) -> Tuple[Optional[float], Optional[float], Optional[int]]:
    best_f1 = best_acc = None
    best_ep = None
    if not metrics_csv.is_file():
        return None, None, None
    with metrics_csv.open(encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row.get("phase") != "val":
                continue
            f1 = _f(row.get("f1"))
            acc = _f(row.get("accuracy"))
            if f1 is not None:
                if best_f1 is None or f1 > best_f1:
                    best_f1 = f1
                    best_ep = int(row.get("epoch", 0))
            if acc is not None:
                best_acc = acc if best_acc is None else max(best_acc, acc)
    return best_f1, best_acc, best_ep


def resolve_run(job: Dict[str, Any]) -> Optional[str]:
    run_dir = job.get("run_dir")
    if run_dir and (LOG_DIR / run_dir / "metrics.csv").is_file():
        return run_dir
    prefix = f"SDAVT_R4_{job['id']}"
    for p in sorted(LOG_DIR.glob(f"{prefix}*/metrics.csv")):
        return p.parent.name
    if (LOG_DIR / prefix / "metrics.csv").is_file():
        return prefix
    return None


def champion_rows(jobs: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    by_ds: Dict[str, List[Dict[str, Any]]] = {"meld": [], "mosei": [], "crema": []}
    for j in jobs:
        if j.get("status") != "done":
            continue
        ds = j.get("dataset")
        if ds not in by_ds:
            continue
        run = resolve_run(j)
        f1, acc, ep = (None, None, None)
        if run:
            f1, acc, ep = read_best(LOG_DIR / run / "metrics.csv")
        f1 = f1 if f1 is not None else j.get("best_val_f1")
        acc = acc if acc is not None else j.get("best_val_acc")
        ep = ep if ep is not None else j.get("best_val_f1_ep")
        by_ds[ds].append(
            {
                "job_id": j["id"],
                "phase": j.get("phase"),
                "f1": f1,
                "acc": acc,
                "ep": ep,
                "run_dir": run or j.get("run_dir"),
            }
        )
    champs = []
    for ds, rows in by_ds.items():
        if not rows:
            continue
        if ds == "crema":
            best = max(rows, key=lambda r: r["acc"] or 0)
            metric = "acc"
        else:
            best = max(rows, key=lambda r: r["f1"] or 0)
            metric = "f1"
        best["dataset"] = ds
        best["metric"] = metric
        champs.append(best)
    return champs


def build_queue_table(jobs: List[Dict[str, Any]]) -> str:
    lines = [
        "<!-- AUTO-GENERATED by build_master_doc_metrics.py -->",
        f"<!-- generated_at: {datetime.now(timezone.utc).isoformat()} -->",
        "",
        "| Phase | Job | Dataset | Status | Best F1 | Best Acc | Run |",
        "|-------|-----|---------|--------|---------|----------|-----|",
    ]
    for j in sorted(jobs, key=lambda x: (x.get("phase", ""), x.get("id", ""))):
        run = resolve_run(j) or j.get("run_dir") or "—"
        f1 = j.get("best_val_f1")
        acc = j.get("best_val_acc")
        f1s = f"{f1:.4f}" if isinstance(f1, (int, float)) else "—"
        accs = f"{acc:.4f}" if isinstance(acc, (int, float)) else "—"
        lines.append(
            f"| {j.get('phase','')} | {j.get('id','')} | {j.get('dataset','')} | "
            f"{j.get('status','')} | {f1s} | {accs} | `{run}` |"
        )
    return "\n".join(lines) + "\n"


def build_champion_table(champs: List[Dict[str, Any]]) -> str:
    lines = [
        "<!-- AUTO-GENERATED champions -->",
        "",
        "| Dataset | Champion Job | Best F1 | Best Acc | Epoch | Run |",
        "|---------|--------------|---------|----------|-------|-----|",
    ]
    for c in champs:
        f1 = f"{c['f1']:.4f}" if c.get("f1") is not None else "—"
        acc = f"{c['acc']:.4f}" if c.get("acc") is not None else "—"
        ep = c.get("ep") if c.get("ep") is not None else "—"
        lines.append(
            f"| {c['dataset']} | **{c['job_id']}** | {f1} | {acc} | {ep} | `{c.get('run_dir','—')}` |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    q = json.loads(QUEUE_FILE.read_text(encoding="utf-8"))
    jobs = q.get("jobs", [])
    status = Counter(j.get("status") for j in jobs)
    audit = {}
    if AUDIT_FILE.is_file():
        audit = json.loads(AUDIT_FILE.read_text(encoding="utf-8"))

    snippet = build_queue_table(jobs)
    snippet += "\n## Queue summary\n\n"
    snippet += f"- Total jobs: **{len(jobs)}**\n"
    for k, v in sorted(status.items()):
        snippet += f"- `{k}`: {v}\n"
    if audit:
        snippet += f"- Audit P0: **{audit.get('p0', '—')}** | collapses: {audit.get('collapses', '—')}\n"

    SNIPPET.write_text(snippet, encoding="utf-8")
    CHAMPION_SNIPPET.write_text(build_champion_table(champion_rows(jobs)), encoding="utf-8")
    print(f"[OK] wrote {SNIPPET}")
    print(f"[OK] wrote {CHAMPION_SNIPPET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
